version: '3'
services:
  mysql:
    image: mysql:8.0.32
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysql_db:/var/lib/mysql
  backend_convoi_lourd:
    image: backend_convoi_lourd:1.0
    ports:
      - '3001:3001'
    volumes:
      - server_code:/app
volumes:
  mysql_db:
    driver: local
  server_code:
    driver: local

